```{r}
#| echo: false
source("_common.R")
.gh_url <- file.path('https://github.com', rmarkdown::metadata[['github-repo']])
```

# Welcome {-}

This package is used to support the OHCA package demonstration at the Bioconductor Conference 2023. 

::: {.callout-tip icon='true'}
## 📚 The OHCA book is the main documentation, and is available [here](https://jserizay.com/OHCA/). {.unnumbered .unlisted}
:::

## Description

This is a package demonstration for the `OHCA` ecosystem, including the 
following packages : 

- `HiCool`
- `HiCExperiment`
- `HiContacts`
- `fourDNData`

## Pre-requisites

* Familiarity with the `tidyverse` syntax; 
* Familiarity with the `GenomicRanges` class; 
* Basic understanding of Hi-C principles

For more information on Hi-C experimental approach and principles, 
read [OHCA book first chapter](https://jserizay.com/OHCA/principles.html).

## Time outline

| Activity                     | Time |
|------------------------------|------|
| Introduction to Hi-C         | 10m  |
| OHCA ecosystem               | 10m  |
| Demonstration with real data | 20m  |
| Wrapping up                  | 5m   |

## Docker image

To quickly use the package Docker image:

```sh
docker run -it -e PASSWORD=OHCA -p 8787:8787 ghcr.io/js2264/ohca:bioc_RELEASE_3_17
```
Once running, navigate to http://localhost:8787/ and then login 
with `rstudio`:`OHCA`. 

