---
title: "How To Build A Workshop Package"
subtitle: "In other words, how do I use what's here"
author: Sean Davis^[seandavi@gmail.com]
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{How to Use this Package to Build a Bioc Workshop}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

First, this package doesn't do much except add a template Github Action to
build all the pieces necessary for a workshop.

## Quickstart

- [x] Create a repo from this template and rename it (do not fork the repository).
  - [x] Ensure that "Read and Write Permissions" is checked under [General > Workflow permissions](https://github.com/seandavi/BuildABiocWorkshop/settings/actions). 
- [X] Edit `DESCRIPTION` file
  - [x] Change package name
  - [x] Change title and description
  - [x] Change authors
  - [x] Check dependencies
  - [x] Change DockerImage tag
- [X] Edit '_pkgdown.yml' (and `.github/workflows yaml file` as needed)
- [x] Write a normal R package that can be installed
- [x] Include one or more vignettes that will constitute the workshop materials


### 5. Edit `.github/workflows yaml` as needed (likely no need)


You do not need to create a docker image manually. Github actions will read Dockerfile located in this template, and using the yaml files will create, build and push to the Github Container Registry an image with the name (default) `ghcr.io/yourgithubuser/yourgithubreponame`, all lowercase. 


In the DESCRIPTION file, the **DockerImage: should match your the docker image name (should be lowercase)**.


### 6. Edit README.md, add vignettes to vignettes folder
  
Edit the README.md. and add one or more Rmd vignettes that will constitute the workshop materials. It is normal R package that should pass `rcmdcheck::rcmdcheck()`, and be installed using regular R package install commands.  


